mywebsite/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
from person_detector import views as viewsPersonDetector

from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.login_page, name='login'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('', views.index, name='landing-page'),
    path('person-detector/', include('person_detector.urls')),
    path('memory-tray-detector/', include('memory_tray_detector.urls')),
    path('trash-can-detector/', include('trash_can_detector.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

person_detector/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name = 'person_detector'
urlpatterns = [
    path('', views.home, name='home'),
    path('database/', views.database, name='database'),
    path('database/add/', views.post_database, name='add-database'),
    # path('database/train/', views.train_data, name='train_data'),
    path('open/', views.cam, name='open_cam'),
    path('database/delete/<int:delete_id>', views.delete, name='delete_data'),
    path('database/delete-checkbox/', views.person_delete_checkbox, name='delete-person-checkbox'),
    path('database/delete-all/', views.person_delete_all, name='delete-person-all'),
    path('database/update/<int:update_id>', views.update, name='update_data'),
    path('database/update-ip-camera/<int:update_id>', views.update_ip_camera, name='update_ip_camera'),
    path('reset-all-detected-face/', views.reset_all, name='reset-all-detected-face'),
    path('export/', views.export_detected_dace, name='export-detected-face'),
    # path('gallery/', views.gallery, name='gallery'),
]

person_detector/models.py
from django.db import models

import os

# untuk menambahkan data person
class Post(models.Model):
    name = models.CharField(max_length=20)
    fullName = models.CharField(max_length=50)
    date_created = models.DateField(auto_now_add=True)
    picture = models.ImageField(upload_to='person_detector', null=True)

    def __str__(self):
        return self.name
    
    def delete(self, *args, **kwargs):
        self.picture.delete()
        super().delete(*args, **kwargs)  

# untuk menyimpan person yang terdeteksi
class DetectedFace(models.Model):
    name = models.CharField(max_length=100)
    detected_time = models.DateTimeField()
    detected_day = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"{self.name} ({self.detected_time})"
    
# Untuk menyimpan addres Ip Camera
class IpCamera(models.Model):
    name = models.CharField(max_length=20)
    ip_camera = models.CharField(max_length=50, null=True)

    def __str__(self):
        return self.name
    
    class Meta:
        get_latest_by = 'id'

person_detector/forms.py
from django import forms
from .models import Post, IpCamera

class PostForm(forms.ModelForm):
    picture = forms.ImageField(label="Picture", widget=forms.FileInput(attrs={'class': 'form-control'}))
    class Meta:
        model = Post
        fields = [
            'name',
            'fullName',
            'picture'
        ]
    
        widgets = {
            'name': forms.TextInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'Fill with one word and this field can\'t be updated'
                }
            ),
            'fullName': forms.TextInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'Fill with your full name'
                },
            ),
        }

class IpCameraForm(forms.ModelForm):
    class Meta:
        model = IpCamera
        fields = [
            'name',
            'ip_camera'
        ]

        widgets = {
            'name': forms.TextInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'Fill with your name Ip Camera'
                }
            ),
            'ip_camera': forms.TextInput(
                attrs = {
                    'class': 'form-control',
                    'placeholder': 'Fill with your IP Camera Address'
                },
            ),
        }

        

person_detector/views.py
from django.shortcuts import render, redirect, HttpResponse
from django.contrib import messages
from .models import Post, DetectedFace, IpCamera
from .forms import PostForm, IpCameraForm
from django.http import HttpResponse
# from .ml_models.test import train
from .ml_models.main2 import open_camera
from .filters import DatabaseFilter, DetectedFilter
from django.conf import settings
from datetime import date
from .resource import DetectedFaceResource
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required, permission_required, user_passes_test
from django.contrib.auth.models import Group, User

import os


@login_required(login_url='login')
def home(request):
    detected = DetectedFace.objects.all().order_by('-id')
    myFilters = DetectedFilter(request.GET, queryset=detected)

    detected = myFilters.qs
    total_data = len(detected) #untuk menghitung jumlah object

    # print(request.user.get_all_permissions())

    context = {
        'title' : 'Person Detector | Home',
        'detected': detected,
        'myFilters': myFilters,
        'total_data': total_data
    }

    return render(request, 'person_detector/home.html', context)

@login_required(login_url='login')
def export_detected_dace(reqeust):
    detected_face = DetectedFaceResource()
    dataset = detected_face.export()
    response = HttpResponse(dataset.csv, content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename=all_detectted_face_record.csv'
    return response

camera_open = False
@login_required(login_url='login')
def cam(request):
    # if request.method == 'GET':
    #     success, error = open_camera()

    #     if success:
    #         messages.success(request, 'Camera Has Been Succesfully Opened')
    #     else:
    #         messages.error(request, f'Camera Cannot Opened with error: {error}')
    global camera_open
    if request.method == 'GET':
        camera = IpCamera.objects.latest()
        print(camera.ip_camera)
        if not camera_open:
            try:
                camera_open = True
                open_camera()

                camera_open = False
            except Exception as e:
                camera_open = False
                error_message = f"Kamera tidak dapat terbuka. Kesalahan: {str(e)}"
                messages.error(request, error_message)
        else:
             messages.error(request, 'Camera is currently open')
        
        print('OK')
    return redirect('person_detector:home')

@login_required(login_url='login')
def database(request):
    post_person = Post.objects.all()
    ip_camera = IpCamera.objects.all()
    myFilters = DatabaseFilter(request.GET, queryset=post_person)
    post_person = myFilters.qs
    total_data = len(post_person) #untuk menghitung jumlah object
    context = {
        'title' : 'Person Detector | Database',
        'post': post_person,
        'myFilters': myFilters,
        'total_data': total_data,
        'ip_camera': ip_camera
    }
    return render(request, 'person_detector/database.html', context)



@login_required(login_url='login')
def post_database(request):
    post_person = Post.objects.all() 
    post_form = PostForm(request.POST or None, request.FILES)
    if request.method == "POST":
        if post_form.is_valid():
            name = post_form.cleaned_data['name']
            
            # validasi agar name yang diinput tidak sama dengan name yang sudah ada
            if Post.objects.filter(name=name).exists():
                messages.error(request, f'{name} already exists in the database.')
                return redirect('person_detector:database')

            picture = request.FILES['picture']
            post = post_form.save(commit=False)
            post.picture = picture

            ext = picture.name.split('.')[-1] #mendapatkan ekstensi
            filename = f'{name}.{ext}'
            post.picture.name = filename
            post.save()

            for person in post_person:
                name = person.name           
            messages.success(request, f'{name} successfully added')
            return redirect('person_detector:database')
    
    myFilters = DatabaseFilter(request.GET, queryset=post_person)
    post_person = myFilters.qs  
    context = {
        'title': 'Add Database',
        'action': 'Submit',
        'post_form': post_form,
        'post': post_person,
        'myFilters': myFilters
    }
    return render(request, 'person_detector/add_database.html', context)

# def train_data(request):
#     image_folder = 'static/images/person_detector/'
#     folder = os.path.join(settings.BASE_DIR, image_folder)
    
#     train(folder)

#     if True:
#         messages.success(request, 'Data berhasil ditrain')
#         return redirect('person_detector:database')

@login_required(login_url='login')
def delete(request, delete_id):
    objcet = Post.objects.get(id = delete_id)
    objcet.delete()
    pesan = 'Data deleted successfully'            
    messages.success(request, pesan)
    return redirect('person_detector:database')

@login_required(login_url='login')
def update(request, update_id):
    post_person = Post.objects.all()
    form = Post.objects.get(id = update_id)
    name = form.name

    if request.method == 'POST' :
        # name = request.POST.get('name')
        if len(request.FILES) != 0:
            if len(form.picture) > 0:
                os.remove(form.picture.path)
            picture = request.FILES['picture']
            form.picture = picture

            ext = picture.name.split('.')[-1] #mendapatkan ekstensi
            filename = f'{name}.{ext}'
            form.picture.name = filename

        
        form.fullName = request.POST.get('fullName')


        form.save()

        messages.success(request, 'Data successfully updated')
        return redirect('person_detector:database')
    
    context = {
        'title': 'Update Person Database',
        'form': form,
        'action': 'Update',
        'post': post_person,
    }

    return render(request, 'person_detector/update_database.html', context)

# Update Ip Camera address
@login_required(login_url='login')
def update_ip_camera(request, update_id):
    post_person = Post.objects.all()
    ip_camera = IpCamera.objects.all()
    ip_cam_update = IpCamera.objects.get(id = update_id)

    if request.method == 'POST':
        # Membuat form untuk mengupdate data Camera
        form_ip_cam_update = IpCameraForm(request.POST or None, instance=ip_cam_update)
        
        if form_ip_cam_update.is_valid():

            # Menyimpan perubahan pada instance Camera
            form_ip_cam_update.save()

            messages.success(request, 'Updated Succes')
            return redirect('person_detector:database')
    else:
        # Membuat form untuk mengupdate data Camera dengan menggunakan instance yang sudah ada
        form_ip_cam_update = IpCameraForm(instance=ip_cam_update)
        
        context = {
            'title': 'Update Ip Camera',
            'action': 'Update',
            'form': form_ip_cam_update,
            'post': post_person,
            'ip_camera': ip_camera
        }
    return render(request, 'person_detector/update_ip_camera.html', context)


@login_required(login_url='login')
def reset_all(request):
    obj = DetectedFace.objects.all()
    obj.delete()

    messages.success(request, f'All detected faces have been successfully deleted.')
    return redirect('person_detector:home')


# Menghapus data berdasarkan checkbox pada database person
@login_required(login_url='login')
def person_delete_checkbox(request):
    if request.method == 'POST':
        # Mengambil daftar ID person yang dipilih dari permintaan POST
        person_ids = request.POST.getlist('person_ids')

        # Menghapus setiap objek person berdasarkan ID yang dipilih
        for i in person_ids:
            obj = Post.objects.get(id=i)
            obj.delete()

        # Menampilkan pesan sukses jika ada data yang dihapus, atau pesan bahwa tidak ada data yang dipilih
        if len(person_ids) == 0:
            messages.success(request, 'No data selected')
        else:
            messages.success(request, f'{len(person_ids)} data have been successfully deleted')

    # Mengarahkan pengguna kembali ke halaman database setelah menghapus data
    return redirect('person_detector:database')


# Menghapus semua data person
@login_required(login_url='login')
def person_delete_all(request):
    # Mengambil semua ID camera menggunakan values_list
    person_ids = Post.objects.values_list('id', flat=True)

    # Menghapus setiap objek camera berdasarkan ID
    for i in person_ids:
        obj = Post.objects.get(id=i)
        obj.delete()

    # Menampilkan pesan sukses jika ada data yang dihapus, atau pesan bahwa tidak ada data yang harus dihapus
    if len(person_ids) == 0:
        messages.success(request, 'No data should be deleted')
    else:
        messages.success(request, 'All data have been successfully deleted')

    # Mengarahkan pengguna kembali ke halaman database setelah menghapus data
    return redirect('person_detector:database')

person_detector/templates/person_detector/add_database.html
{% extends 'person_detector/database.html' %}

{% block add_database %}
        
        <div class="container shadow rounded mt-3">
            <h5>{{title}}</h5>
            <form method="POST" enctype="multipart/form-data" class="col">
                {% csrf_token %}
                    
                {% for form in post_form %}
                    <div class="col-auto">
                        {{form.label}}
                    </div>                        
                            
                    <div class="col-auto">
                        {{form}}
                    </div>
                {% endfor %}
                {% if update_data.picture %}
                    <img src="{{update_data.picture.url}}" alt="" width="90px">
                {% endif %} 

                <div>
                    <button type="submit" class="btn btn-success my-4">{{action}}</button>
                    <a href="{% url 'person_detector:database' %}" class="btn btn-danger">Back</a>
                </div>

            </form>
        </div>
{% endblock add_database %}


    

person_detector/templates/person_detector/database.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
    {{title}}
{% endblock title %}


{% block list %}
  <li class="nav-item ps-4">
    <a class="nav-link" href="{% url 'person_detector:home' %}">Home</a>
  </li>
  <li class="nav-item ps-4">
    <a class="nav-link active" aria-current="page" href="{% url 'person_detector:database' %}">Database</a>
  </li>
  <li class="nav-item ps-4">
    <a class="nav-link" href="" data-bs-toggle="modal" data-bs-target="#logout-user">Logout</a>
  </li>
{% endblock list %}
  


{% block content %}    
    {% block add_database %}
        
    {% endblock add_database %}
    
    <div class="container mt-3" style="font-family: 'Poppins', sans-serif; font-weight: 400;">

      <!-- modal untuk logout -->
      <div class="modal fade" id="logout-user" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog modal-dialog-centered">
          <div class="modal-content">
            <div class="modal-header bg-main text-light">
              <h1 class="modal-title fs-5" id="exampleModalLabel">LOGOUT</h1>
              <button type="button" class="btn-close bg-light" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              Are you sure to <strong>Logout</strong>?
            </div>
            <div class="modal-footer">
              <a href="{% url 'logout' %}" class="btn btn-danger">Logout</a>
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
            </div>
          </div>
        </div>
      </div>

      <div class="d-flex justify-content-between">
        <h5>Person Detector | Database </h5>
        <h5>Active | {{user.first_name}}</h5>
      </div>

      
      <!-- messages -->
      <div>
        {% if messages %}
         {% for msg in messages %}
            <div class="alert {% if msg.tags == 'success' %}alert-success{% elif msg.tags == 'error' %}alert-danger{% endif %} alert-dismissible fade show d-sm-inline-flex" role="alert">
                {{ msg }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
          {% endfor %}
        {% endif %}
      </div>

      <!-- Tabel IP CAMERA-->
        <table class="table table-striped table-hover table-bordered table-sm rounded rounded-lg shadow">
          <thead>
            <tr>
              <th scope="col" class="text-center">Name</th>
              <th scope="col" class="text-center">IP Camera Address</th>
              <th scope="col" class="text-center">Update</th>
            </tr>
          </thead>
          <tbody>
            {% for data in ip_camera %}
              <tr>
                <td class="text-center align-middle">{{data.name}}</td>
                <td class="text-center align-middle">{{data.ip_camera}}</td>
                <td class="text-center align-middle">
                  <a href="{% url 'person_detector:update_ip_camera' data.id %}" class="btn btn-sm btn-warning">Update</a>
                </td>
              </tr>
            {% endfor %}             
          </tbody>
        </table>
      <!-- Akhir Tabel IP CAMERA-->

      <div class="d-flex justify-content-between">
        <a href="{% url 'person_detector:add-database' %}" class="btn btn-primary my-1">Add Person</a>

      <!-- <p class="mb-0 mt-0 d-flex align-items-end">Current Data : <strong>{{total_data}}</strong></p> -->
      </div>
      


      <!-- Filter -->
      <div class="row mt-2 mb-2">
        <div class="col">
          <div class="card card-body">
            <div class="d-flex justify-content-between">
              <div>
                <form method="GET" class="row g-2 align-items-center">
                  <div class="col-auto align-middle">
                    {{myFilters.form.name.label}}
                  </div>
                  <div class="col-auto">
                    {{myFilters.form.name}}
                  </div>                    
                  <div class="col-auto">
                    <button type="submit" class="btn btn-primary">Search</button>
                  </div>
                  <div class="col-auto">
                    <a href="{% url 'person_detector:database' %}" class="btn btn-danger">Back to See All</a>
                  </div>
    
                  
                </form>
              </div>
              
              <p class="mb-0 mt-0 d-flex align-items-center">Current Data : <strong>{{total_data}}</strong></p>
            </div>
          </div>
        </div>
      </div>
      <!-- Akhir -->

      

      <!-- Tabel -->
      <div class="scroll">
       <form action="{% url 'person_detector:delete-person-checkbox' %}" method="post">
        {% csrf_token %}
        <table class="table table-striped table-hover table-bordered table-sm rounded rounded-lg">
          <thead>
            <tr>
              <th scope="col" class="text-center align-middle">No.</th>
              <th scope="col" class="text-center align-middle">Picture</th>
              <th scope="col" class="text-center align-middle">Name</th>
              <th scope="col" class="text-center align-middle">Full Name</th>
              <th scope="col" class="text-center align-middle">Date Created</th>
              <th scope="col" class="text-center align-middle">
                Delete
                <div class="btn-group">
                  <button type="button" class="btn btn-sm bg-main text-light dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"></button>
                  <ul class="dropdown-menu">
                    <li><button type="button" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#delete-all-data">Delete All</button></li>
                  </ul>
              </th>
               <!-- Modal Delete All-->
               <div class="modal fade" id="delete-all-data" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                  <div class="modal-content">
                    <div class="modal-header bg-main text-light">
                      <h1 class="modal-title fs-5" id="exampleModalLabel">DELETE</h1>
                      <button type="button" class="btn-close bg-light" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      Are you sure to delete <strong>All Data</strong>?
                    </div>
                    <div class="modal-footer">
                      <a href="{% url 'person_detector:delete-person-all' %}" class="btn btn-danger">Delete</a>
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    </div>
                  </div>
                </div>
              </div>
              <!-- Akhir modal -->
              <th scope="col" class="text-center align-middle">Update</th>
              <th scope="col" class="text-center align-middle">
                <button type="button" class="btn btn-sm btn-danger" data-bs-toggle="modal" data-bs-target="#delete-selected">Delete</button>
              </th>
               <!-- Modal Delete Selected-->
               <div class="modal fade" id="delete-selected" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                  <div class="modal-content">
                    <div class="modal-header bg-main text-light">
                      <h1 class="modal-title fs-5" id="exampleModalLabel">DELETE</h1>
                      <button type="button" class="btn-close bg-light" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      Are you sure to delete the data of <strong>Selected Data</strong>?
                    </div>
                    <div class="modal-footer">
                      <button type="submit" class="btn btn-danger">Delete</button>
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    </div>
                  </div>
                </div>
              </div>
              <!-- Akhir modal -->
              
            </tr>
          </thead>
          <tbody>
            {% for data in post %}
              <tr>
                <td scope="row" class="text-center align-middle">{{forloop.counter}}</td>
                <td class="text-center align-middle">                 
                  {% if data.picture %}
                   <!-- <img src="{{data.picture.url}}" alt="" width="90px"> -->
                   <button type="button" class="btn btn-light" data-bs-toggle="modal" data-bs-target="#photo-{{data.id}}">
                    <img src="{{data.picture.url}}" alt="" width="90px">
                 </button>
                  {% endif %}                  
                </td>
                <!-- Modal Photo -->
                <div class="modal fade" id="photo-{{data.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                      <div class="modal-header bg-main text-light">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">{{data.name}} </h1>
                        <button type="button" class="btn-close bg-light" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body text-center">
                        <img src="{{data.picture.url}}" alt="" width="450px">
                      </div>
                    </div>
                  </div>
                </div>
                 <!--Akhir Modal  -->
                <td class="text-center align-middle">{{data.name}}</td>
                <td class="text-center align-middle">{{data.fullName}}</td>
                <td class="text-center align-middle">{{data.date_created}}</td>
                <td class="text-center align-middle">
                  <button type="button" class="btn btn-sm btn-danger" data-bs-toggle="modal" data-bs-target="#delete-{{data.id}}">
                    Delete
                  </button>
                </td>
                <!-- Modal -->
                <div class="modal fade" id="delete-{{data.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                      <div class="modal-header bg-main text-light">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">DELETE</h1>
                        <button type="button" class="btn-close bg-light" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                        Are you sure to delete <strong>"{{data.name}}"</strong> data?
                      </div>
                      <div class="modal-footer">
                        <a href="{% url 'person_detector:delete_data' data.id %}" class="btn btn-danger">Delete</a>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                      </div>
                    </div>
                  </div>
                </div>
                <td class="text-center align-middle">
                  <a href="{% url 'person_detector:update_data' data.id %}" class="btn btn-sm btn-warning">Update</a>
                </td>
                <td class="text-center align-middle">
                  <input type="checkbox" class="person-checkbox" name="person_ids" value="{{data.id}}">
                </td>
              </tr>
            {% endfor %}             
          </tbody>
        </table>
       </form>
      </div>
      <!-- Akhir Tabel -->

    </div>    
         
    
    <script>
      // Mengambil semua elemen checkbox dengan class 'camera-checkbox'
      const checkboxes = document.querySelectorAll('.person-checkbox');
  
      // Mendaftarkan event listener untuk setiap checkbox
      checkboxes.forEach(checkbox => {
        // Menambahkan event listener untuk klik pada kotak centang
        checkbox.addEventListener('click', (event) => {
          // Mencegah klik pada kotak centang mempengaruhi perilaku
          event.stopPropagation();
        });
  
        // Menambahkan event listener untuk klik pada kolom
        checkbox.parentNode.addEventListener('click', (event) => {
          // Toggle status kotak centang saat kolom diklik
          checkbox.checked = !checkbox.checked;
        });
      });
    </script>
{% endblock content %}
    
    

person_detector/templates/person_detector/gallery.html
{% extends 'base.html' %}

{% block list %}
<li class="nav-item ps-4">
    <a class="nav-link" href="{% url 'person_detector:home' %}">Home</a>
  </li>
  <li class="nav-item ps-4">
    <a class="nav-link" href="{% url 'person_detector:database' %}">Database</a>
  </li>
  <li class="nav-item ps-4">
    <a class="nav-link" href="{% url 'person_detector:logout' %}">Logout</a>
  </li>    
{% endblock list %}
    

{% block title %}
    {{title}}
{% endblock title %}
    

person_detector/templates/person_detector/login.html
{% extends 'base.html' %}


{% block title %}
    {{title}}    
{% endblock title %}

    

{% block content %}
 <div class="container">

 
    <!-- messages -->
 {% if messages %}
 {% for msg in messages %}
     <div class="alert {% if msg.tags == 'success' %}alert-success{% elif msg.tags == 'error' %}alert-danger{% endif %} alert-dismissible fade show d-sm-inline-flex mt-2" role="alert">
         {{ msg }}
         <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
     </div>
 {% endfor %}
{% endif %}


<!-- Login Card -->
    <div class="row d-flex justify-content-center mt-5">
        <div class="col-md-4">
            <div class="card shadow">
                <div class="card-header bg-main text-light align-middle">
                    <h6 class="text-center">LOGIN PAGE | PERSON DETECTOR</h6>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
    
                        <div class="col-auto">
                            <label for="username" class="form-label">Username:</label>
                            <input type="text" class="form-control" id="username" name="username">
                          </div>
                          <div class="mb-3">
                            <label for="password" class="form-label">Password</label>
                            <input type="password" class="form-control" id="password" name="password">
                          </div>
    
                          <button type="submit" class="btn btn-primary">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
 </div>    

{% endblock content %}
    

person_detector/templates/person_detector/update_ip_camera.html
{% extends 'person_detector/database.html' %}


{% block add_database %}

<div class="container shadow rounded mt-3">
    <h5>{{title}}</h5>
    <form method="POST" enctype="multipart/form-data" class="col">
        {% csrf_token %}
            
        {% for form in form %}
            <div class="col-auto">
                {{form.label}}
            </div>                        
                    
            <div class="col-auto">
                {{form}}
            </div>
        {% endfor %}

        <div>
            <button type="submit" class="btn btn-success my-4">{{action}}</button>
            <a href="{% url 'person_detector:database' %}" class="btn btn-danger">Back</a>
        </div>

    </form>
</div>
    
{% endblock add_database %}
    