memory_tray_detector/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name = 'memory_tray_detector'
urlpatterns = [
    path('', views.home, name='home'),
    path('open-cam/<int:camera_id>/', views.open_cam, name='open-cam'),
    # path('open-cam-local/<int:camera_id>/', views.open_cam_local, name='open-cam-local'),
    path('camera/', views.camera, name='camera'),
    path('camera/add', views.add_camera, name='add-camera'),
    path('camera/delete/<int:delete_id>', views.delete, name='delete-camera'),
    path('camera/delete-checkbox/', views.camera_delete_checkbox, name='delete-camera-checkbox'),
    path('camera/delete-all/', views.camera_delete_all, name='delete-camera-all'),
    path('camera/update/<int:update_id>', views.update, name='update-camera'),
    path('gallery/', views.gallery, name='gallery'),
    path('gallery/delete/<int:delete_id>', views.delete_gallery, name='delete-gallery'),
    path('gallery/delete-checkbox/', views.gallery_delete_checkbox, name='delete-gallery-checkbox'),
    path('gallery/delete-all/', views.gallery_delete_all, name='delete-gallery-all'),    
]

mywebsite/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
from person_detector import views as viewsPersonDetector

from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.login_page, name='login'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('', views.index, name='landing-page'),
    path('person-detector/', include('person_detector.urls')),
    path('memory-tray-detector/', include('memory_tray_detector.urls')),
    path('trash-can-detector/', include('trash_can_detector.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

memory_tray_detector/models.py
from django.db import models
from django.db.models.signals import post_save, pre_delete
from django.dispatch import receiver

# Models untuk Camera
class Camera(models.Model):
    name = models.CharField(max_length=20)
    description = models.CharField(max_length=100, null=True)
    ip_camera = models.CharField(max_length=200,null=True)
    date_created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

# Models untuk input image dengan POST
class ListCamera(models.Model):
    name = models.ForeignKey(Camera, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to='memory_tray_detector', null=True)

    def __str__(self):
        return self.name

# Ketika suatu instance Camera ditambahkan oleh user, maka satu CamCard akan dibuat secara otomatis
@receiver(post_save, sender=Camera)
def create_camcard(sender, instance, created, **kwargs):
    if created:
        CamCard.objects.create(name=instance)

# Models untuk Card yang digunakan untuk menampung informasi dari object yang dipotret yang ditampilkan di page Home
class CamCard(models.Model):
    name = models.ForeignKey(Camera, on_delete=models.CASCADE)

    def __str__(self):
        return self.name.name
    
# Models untuk Gallery 
class Gallery(models.Model):
    name = models.ForeignKey(Camera, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to='memory_tray_detector', null=True)
    quantity = models.IntegerField(null=True)
    timestamp = models.DateTimeField()
    detected_day = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name.name
    
    def delete(self, *args, **kwargs):
        self.picture.delete()
        super().delete(*args, **kwargs) 

    class Meta:
         get_latest_by = 'id' 

# Ketika instance Camera dihapus, picture pada class Gallery juga akan dihapus
@receiver(pre_delete, sender=Camera)
def delete_picture(sender, instance, **kwargs):    
    # Menghapus gambar pada class Gallery yang menggunakan Camera sebagai foreign key
    for gallery in Gallery.objects.filter(name=instance):
        gallery.delete()

memory_tray_detector/forms.py
from django import forms
from .models import Camera, ListCamera

# Form untuk user menambahkan Camera
class AddCameraForm(forms.ModelForm):
    class Meta:
        model = Camera
        fields = [
            'name',
            'description',
            'ip_camera'
        ]

        widgets = {
            'name': forms.TextInput(
                attrs= {
                    'class': 'form-control',
                    'placeholder': 'This field can not be modified'
                }
            ),
            'description': forms.TextInput(
                attrs= {
                    'class': 'form-control',
                    'placeholder': 'Fill the description'
                }
            ),
            'ip_camera': forms.TextInput(
                attrs= {
                    'class': 'form-control',
                    'placeholder': 'If no ip camera, fill with \'-\', \'None\', or \'none\''
                }
            )
        }

class ListCameraForm(forms.Form):
    name = forms.ModelChoiceField(queryset=Camera.objects.all(), label='Select Memory Tray',widget=forms.Select(attrs={'class': 'form-select'}))
    picture = forms.ImageField(label="Image", widget=forms.FileInput(attrs={'class': 'form-control'}))
    class Meta:
        model = ListCamera
        fields = [
            'name',
            'picture'
        ]

memory_tray_detector/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Camera, CamCard, Gallery
from .forms import AddCameraForm, ListCameraForm
from .filters import CameraFilter, GalleryFilter
from .ml_models.camera import open_camera
from django.conf import settings
from datetime import datetime
from django.utils import timezone
from .ml_models.camera import send_message_to_mqtt
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import Group, User

import os


# Page Home
@login_required(login_url='login')
def home(request):
    # Mengakses semua instance CamCard
    cam_card = CamCard.objects.all()
    
    # Membuat form untuk input data camera
    forms = ListCameraForm(request.POST or None, request.FILES)
    
    if request.method == 'POST':
        if forms.is_valid():
            # Mendapatkan data yang diinput dari form
            name = forms.cleaned_data.get('name')
            picture = request.FILES['picture']
            current_time = timezone.now()
            quantity = 1
            
            # Menyimpan data ke dalam model Gallery
            save_to_gallery = Gallery.objects.create(
                name=name,
                picture=picture,
                quantity=quantity,
                timestamp=current_time
            )
            save_to_gallery.save()

            # Mengirim pesan melalui MQTT
            formatted_time = current_time.strftime('%d%m%Y')
            message = {
                'name': str(name),
                'quantity': str(quantity),
                'timestamp': formatted_time
            }
            send_message_to_mqtt(message)

            # Menambahkan pesan keberhasilan
            pesan = f'Success upload image for {name}'
            messages.success(request, pesan)  

    # Menghitung total tray yang ada
    total_tray = len(cam_card)

    latest_galleries = Gallery.objects.all().order_by('name', '-timestamp')
    latest_gallery_dict = {}

    for gallery in latest_galleries:
        if gallery.name_id not in latest_gallery_dict:
            latest_gallery_dict[gallery.name_id] = gallery

    latest_galleries = list(latest_gallery_dict.values())

    # Konteks untuk template
    context = {
        'title': 'Memory Tray Detector | Home',
        'cam_card': cam_card,
        'forms': forms,
        'total_tray': total_tray,
        'latest_galleries': latest_galleries
    }
    return render(request, 'memory_tray_detector/home.html', context)


# Page camera
@login_required(login_url='login')
def camera(request):
    # Mengakses instance Camera
    camera = Camera.objects.all()

    # Mengimplementasikan filters untuk list camera
    myFilters = CameraFilter(request.GET, queryset=camera)
    camera = myFilters.qs

    # Menghitung banyaknya camera
    total_cam = len(camera)

    # Konteks untuk template
    context = {
        'title': 'Memory Tray Detector : Camera',
        'camera': camera,
        'total_cam': total_cam,
        'myFilters': myFilters
    }
    return render(request, 'memory_tray_detector/camera.html', context)


# Membuka IP camera berdasarkan ID instance Camera
camera_open = False
@login_required(login_url='login')
def open_cam(request, camera_id):
    global camera_open

    if request.method == 'GET':

        if not camera_open:
            try:
                camera_open = True
                open_camera(camera_id)

                camera_open = False
            except Exception as e:
                # Tangkap kesalahan dan kirim pesan error ke pengguna
                camera_open = False
                error_message = f"Kamera tidak dapat terbuka. Kesalahan: {str(e)}"
                messages.error(request, error_message)
        else:
            messages.error(request, 'Camera is currently open')

    return redirect('memory_tray_detector:home')


# Menambahkan instance Camera
@login_required(login_url='login')
def add_camera(request):
    # Mengakses semua instance Camera
    camera = Camera.objects.all()
    
    # Membuat form untuk menambahkan data camera
    add_form = AddCameraForm(request.POST or None)
    
    if request.method == 'POST':
        if add_form.is_valid():
            # Mendapatkan data yang diinput dari form
            name = add_form.cleaned_data['name']
            ip_camera = add_form.cleaned_data['ip_camera']

            # Validasi agar name dan ip camera yang diinput tidak sama dengan name yang sudah ada
            if Camera.objects.filter(name=name).exists():
                messages.error(request, f'Nama {name} sudah ada di database.')
                return redirect('memory_tray_detector:camera')
            elif Camera.objects.filter(ip_camera=ip_camera).exists() and ip_camera != 'None' and ip_camera != 'none' and ip_camera != '-':
                messages.error(request, 'Alamat IP Camera sudah ada di database.')
                return redirect('memory_tray_detector:camera')
 
            # Menyimpan data ke dalam model Camera
            add_form.save()

            # Menambahkan pesan keberhasilan
            messages.success(request, 'Added Camera Success')
            return redirect('memory_tray_detector:camera')
   
    # Konteks untuk template
    context = {
        'title': 'Add Camera',
        'action': 'Add',
        'add_form': add_form,
        'camera': camera
    }
    return render(request, 'memory_tray_detector/add_camera.html', context)


# Menghapus instance Camera
@login_required(login_url='login')
def delete(request, delete_id):
    # Mengambil instance Camera berdasarkan ID yang diberikan
    cam_object = Camera.objects.get(id=delete_id)
    
    # Menghapus instance Camera
    cam_object.delete()
    
    # Menambahkan pesan keberhasilan
    messages.success(request, 'Camera berhasil dihapus')

    # Mengarahkan pengguna kembali ke halaman camera
    return redirect('memory_tray_detector:camera')


# Menghapus photo di Gallery
@login_required(login_url='login')
def delete_gallery(request, delete_id):
    # Mengambil instance Gallery berdasarkan ID yang diberikan
    gal_object = Gallery.objects.get(id=delete_id)
    
    # Menghapus instance Gallery
    gal_object.delete()
    
    # Menambahkan pesan keberhasilan
    messages.success(request, 'Deleted Success')

    # Mengarahkan pengguna kembali ke halaman gallery
    return redirect('memory_tray_detector:gallery')


# Untuk Update instance Camera
@login_required(login_url='login')
def update(request, update_id):
    # Mengambil semua instance Camera
    camera = Camera.objects.all()
    
    # Mengambil instance Camera yang akan diupdate berdasarkan ID yang diberikan
    cam_update = Camera.objects.get(id=update_id)
    
    if request.method == 'POST':
        # Membuat form untuk mengupdate data Camera
        form_cam_update = AddCameraForm(request.POST or None, instance=cam_update)
        
        # Menonaktifkan field name agar pengguna tidak dapat mengubahnya
        form_cam_update.fields['name'].disabled = True
        
        if form_cam_update.is_valid():
            # Memeriksa apakah terdapat perubahan pada field ip_camera
            if 'ip_camera' in form_cam_update.changed_data:
                # Jika terdapat perubahan pada field ip_camera
                ip_camera = form_cam_update.cleaned_data['ip_camera']
                
                # Memeriksa apakah alamat IP Camera sudah ada di database
                if Camera.objects.filter(ip_camera=ip_camera).exists() and ip_camera != 'None' and ip_camera != 'none' and ip_camera != '-':
                    messages.error(request, 'Alamat IP Camera sudah ada di database.')
                    return redirect('memory_tray_detector:camera')

            # Menyimpan perubahan pada instance Camera
            form_cam_update.save()

            messages.success(request, 'Updated Succes')
            return redirect('memory_tray_detector:camera')
    else:
        # Membuat form untuk mengupdate data Camera dengan menggunakan instance yang sudah ada
        form_cam_update = AddCameraForm(instance=cam_update)
        
        # Menonaktifkan field name agar pengguna tidak dapat mengubahnya
        form_cam_update.fields['name'].disabled = True
        
        context = {
            'title': 'Update Camera',
            'action': 'Update',
            'add_form': form_cam_update,
            'camera': camera
        }
    
    return render(request, 'memory_tray_detector/add_camera.html', context)


# Page Gallery
@login_required(login_url='login')
def gallery(request):
    # Mengambil semua instance dari model Gallery dan diurutkan berdasarkan ID secara menurun (paling baru)
    gall = Gallery.objects.all().order_by('-id')

    # Menerapkan filter pada list instance di Gallery berdasarkan permintaan GET yang diterima
    myFilters = GalleryFilter(request.GET, queryset=gall)
    gall = myFilters.qs

    # Menghitung jumlah instance di Gallery
    total_pic = len(gall)

    context = {
        'title': 'Memory Tray Detector | Gallery',
        'gallery': gall,
        'myFilters': myFilters,
        'total_pic': total_pic
    }
    return render(request, 'memory_tray_detector/gallery.html', context)


# Menghapus data berdasarkan checkbox pada gallery
@login_required(login_url='login')
def gallery_delete_checkbox(request):
    if request.method == 'POST':
        # Mengambil daftar ID galeri yang dipilih dari permintaan POST
        gallery_ids = request.POST.getlist('gallery_ids')

        # Menghapus setiap objek galeri berdasarkan ID yang dipilih
        for i in gallery_ids:
            obj = Gallery.objects.get(id=i)
            obj.delete()

        # Menampilkan pesan sukses jika ada data yang dihapus, atau pesan bahwa tidak ada data yang dipilih
        if len(gallery_ids) == 0:
            messages.success(request, 'No data selected')
        else:

memory_tray_detector/templates/memory_tray_detector/camera.html
{% extends 'base.html' %}


{% block title %}
    {{title}}
{% endblock title %}
    
{% block list %}
  <li class="nav-item ps-4">
    <a class="nav-link" href="{% url 'memory_tray_detector:home' %}">Home</a>
  </li>
  <li class="nav-item ps-4">
    <a class="nav-link active" aria-current="page" href="{% url 'memory_tray_detector:camera' %}">Camera</a>
  </li>
  <li class="nav-item ps-4">
    <a class="nav-link" href="{% url 'memory_tray_detector:gallery' %}">Gallery</a>
  </li>
  <li class="nav-item ps-4">
    <a class="nav-link" href="" data-bs-toggle="modal" data-bs-target="#logout-user">Logout</a>
  </li>    
{% endblock list %}


{% block content %}
  
  {% block add_camera %}
    
  {% endblock add_camera %}
    
  <div class="container mt-3" style="font-family: 'Poppins', sans-serif; font-weight: 400;">

    <!-- modal untuk logout -->
    <div class="modal fade" id="logout-user" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header bg-main text-light">
            <h1 class="modal-title fs-5" id="exampleModalLabel">LOGOUT</h1>
            <button type="button" class="btn-close bg-light" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            Are you sure to <strong>Logout</strong>?
          </div>
          <div class="modal-footer">
            <a href="{% url 'logout' %}" class="btn btn-danger">Logout</a>
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          </div>
        </div>
      </div>
    </div>

    <!-- Title -->
    <div class="d-flex justify-content-between">
      <h5>Memory Tray Detector | Home </h5>
      <h5>Active | {{user.first_name}}</h5>
    </div>
    <!-- Button Add Camera -->
    <div class="d-flex justify-content-between">
      <a href="{% url 'memory_tray_detector:add-camera' %}" class="btn btn-primary my-1">Add Camera</a>
      <!-- <p class="mb-0 mt-0 d-flex align-items-end">Current Camera : <strong>{{total_cam}}</strong></p> -->
    </div>
    <!-- messages -->
    <div>
      {% if messages %}
        {% for msg in messages %}
            <div class="alert {% if msg.tags == 'success' %}alert-success{% elif msg.tags == 'error' %}alert-danger{% endif %} alert-dismissible fade show d-sm-inline-flex" role="alert">
                {{ msg }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
      {% endif %}
    </div>

     <!-- Filter -->
     <div class="row mt-2 mb-2">
      <div class="col">
        <div class="card card-body">
          <div class="d-flex justify-content-between">
            <div>
              <form method="GET" class="row g-2 align-items-center">
                <div class="col-auto align-middle">
                  {{myFilters.form.name.label}}
                </div>
                <div class="col-auto">
                  {{myFilters.form.name}}
                </div>                    
                <div class="col-auto">
                  <button type="submit" class="btn btn-primary">Search</button>
                </div>
                <div class="col-auto">
                  <a href="{% url 'memory_tray_detector:camera' %}" class="btn btn-danger">Back to See All</a>
                </div>
              </form>
            </div>
              <p class="mb-0 mt-0 d-flex align-items-center">Current Data : <strong>{{total_cam}}</strong></p>
          </div>
        </div>
      </div>
    </div>
    <!-- Akhir -->
    
     <!-- Tabel -->
     <div class="scroll">
      <form action="{% url 'memory_tray_detector:delete-camera-checkbox' %}" method="post">
        {% csrf_token %}
        <table class="table table-striped table-hover table-bordered rounded rounded-lg">
          <thead>
            <tr>
              <th scope="col" class="text-center align-middle">No.</th>
              <th scope="col" class="text-center align-middle">Name</th>
              <th scope="col" class="text-center align-middle">Description</th>
              <th scope="col" class="text-center align-middle">IP Camera</th>
              <th scope="col" class="text-center align-middle">Date Created</th>
              <th scope="col" class="text-center align-middle">
                Delete
                  <div class="btn-group">
                    <button type="button" class="btn btn-sm bg-main text-light dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"></button>
                    <ul class="dropdown-menu">
                      <li><button type="button" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#delete-all-data">Delete All</button></li>
                    </ul>
              </th>
              <!-- Modal Delete All-->
              <div class="modal fade" id="delete-all-data" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                  <div class="modal-content">
                    <div class="modal-header bg-main text-light">
                      <h1 class="modal-title fs-5" id="exampleModalLabel">DELETE</h1>
                      <button type="button" class="btn-close bg-light" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      Are you sure to delete <strong>All Data</strong>?. This action will delete all information and photo in gallery
                    </div>
                    <div class="modal-footer">
                      <a href="{% url 'memory_tray_detector:delete-camera-all' %}" class="btn btn-danger">Delete</a>
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    </div>
                  </div>
                </div>
              </div>
              <!-- Akhir modal -->
              <th scope="col" class="text-center align-middle">Update</th>
              <th scope="col" class="text-center align-middle align-middle">
                <button type="button" class="btn btn-sm btn-danger" data-bs-toggle="modal" data-bs-target="#delete-selected">Delete</button>
              </th>
              <!-- Modal Delete Selected-->
              <div class="modal fade" id="delete-selected" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                  <div class="modal-content">
                    <div class="modal-header bg-main text-light">
                      <h1 class="modal-title fs-5" id="exampleModalLabel">DELETE</h1>
                      <button type="button" class="btn-close bg-light" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      Are you sure to delete the data of <strong>Selected Data</strong>?. This action will delete all of part the <strong>Selected</strong>, include all information and photo in gallery
                    </div>
                    <div class="modal-footer">
                      <button type="submit" class="btn btn-danger">Delete</button>
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    </div>
                  </div>
                </div>
              </div>
              <!-- Akhir modal -->
            </tr>
          </thead>
          <tbody>
            {% for data in camera %}
              <tr>
                <td scope="row" class="text-center align-middle">{{forloop.counter}}</td>
                <td class="text-center align-middle">{{data.name}}</td>
                <td class="text-center align-middle">{{data.description}}</td>
                <td class="text-center align-middle">{{data.ip_camera}}</td>
                <td class="text-center align-middle">{{data.date_created}}</td>
                <td class="text-center align-middle">
                  <button type="button" class="btn btn-sm btn-danger" data-bs-toggle="modal" data-bs-target="#delete-{{data.id}}">
                    Delete
                  </button>
                </td>
                <!-- Modal Delete-->
                <div class="modal fade" id="delete-{{data.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                      <div class="modal-header bg-main text-light">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">DELETE</h1>
                        <button type="button" class="btn-close bg-light" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                        Are you sure to delete the data of <strong>{{data.name}}</strong>?. This action will delete all of part the <strong>{{data.name}}</strong>, include all information and photo in gallery
                      </div>
                      <div class="modal-footer">
                        <a href="{% url 'memory_tray_detector:delete-camera' data.id %}" class="btn btn-danger">Delete</a>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                      </div>
                    </div>
                  </div>
                </div>
                <!-- Akhir Modal -->
                <td class="text-center align-middle">
                  <a href="{% url 'memory_tray_detector:update-camera' data.id %}" class="btn btn-sm btn-warning">Update</a>
                </td>
                <td class="text-center align-middle">
                  <input type="checkbox" class="camera-checkbox" name="camera_ids" value="{{data.id}}">
                </td>
              </tr>
            {% endfor %}             
          </tbody>
        </table>
      </form>
    </div>
    <!-- Akhir Tabel -->
  
  
  
  
  
  </div>

  <script>
    // Mengambil semua elemen checkbox dengan class 'camera-checkbox'
    const checkboxes = document.querySelectorAll('.camera-checkbox');

    // Mendaftarkan event listener untuk setiap checkbox
    checkboxes.forEach(checkbox => {
      // Menambahkan event listener untuk klik pada kotak centang
      checkbox.addEventListener('click', (event) => {
        // Mencegah klik pada kotak centang mempengaruhi perilaku
        event.stopPropagation();
      });

      // Menambahkan event listener untuk klik pada kolom
      checkbox.parentNode.addEventListener('click', (event) => {
        // Toggle status kotak centang saat kolom diklik
        checkbox.checked = !checkbox.checked;
      });
    });
  </script>

{% endblock content %}
  

memory_tray_detector/templates/memory_tray_detector/home.html
{% extends 'base.html' %}


{% block title %}
    {{title}}
{% endblock title %}

{% block list %}
  <li class="nav-item ps-4">
    <a class="nav-link active" aria-current="page" href="{% url 'memory_tray_detector:home' %}">Home</a>
  </li>
  <li class="nav-item ps-4">
    <a class="nav-link" href="{% url 'memory_tray_detector:camera' %}">Camera</a>
  </li>
  <li class="nav-item ps-4">
    <a class="nav-link" href="{% url 'memory_tray_detector:gallery' %}">Gallery</a>
  </li>
  <li class="nav-item ps-4">
    <a class="nav-link" href="" data-bs-toggle="modal" data-bs-target="#logout-user">Logout</a>
  </li>    
{% endblock list %}


{% block content %}
  <div class="container mt-3" style="font-family: 'Poppins', sans-serif; font-weight: 400;">

    <!-- modal untuk logout -->
    <div class="modal fade" id="logout-user" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header bg-main text-light">
            <h1 class="modal-title fs-5" id="exampleModalLabel">LOGOUT</h1>
            <button type="button" class="btn-close bg-light" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            Are you sure to <strong>Logout</strong>?
          </div>
          <div class="modal-footer">
            <a href="{% url 'logout' %}" class="btn btn-danger">Logout</a>
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          </div>
        </div>
      </div>
    </div>

    <div class="d-flex justify-content-between">
      <h5>Memory Tray Detector | Home </h5>
      <h5>Active | {{user.first_name}}</h5>
    </div>

    <!-- messages -->
    <div>
      {% if messages %}
        {% for msg in messages %}
            <div class="alert {% if msg.tags == 'success' %}alert-success{% elif msg.tags == 'error' %}alert-danger{% endif %} alert-dismissible fade show d-sm-inline-flex" role="alert">
                {{ msg }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
      {% endif %}
    </div>

    <!-- alert -->
    <div class="alert alert-primary" role="alert">
      You can predict the tray's memory quantity by uploading a photo via the <strong>POST</strong> button or capturing it directly using the <strong>Open Camera</strong> button below.
    </div>

    <!-- Submit Picture -->
    <div class="row mt-2 mb-2">
      <div class="col">
        <div class="card card-body">
          <div class="d-flex justify-content-between">
            <div>
              <form method="POST" enctype="multipart/form-data" class="row g-2 align-items-center">
                {% csrf_token %}
                <div class="col-auto align-middle">
                  {{forms.name.label}}
                </div>
                <div class="col-auto">
                    {{forms.name}}
                </div>   
                

                <div class="col-auto align-middle">
                  {{forms.picture.label}}
                </div>
                <div class="col-auto">
                  {{forms.picture}}
                </div> 

                
                  
                                 
                <div class="col-auto">
                  <button type="submit" class="btn btn-primary">POST</button>
                </div>
              </form>
            </div>
            <div>
              <p>Total Current Tray : <strong>{{total_tray}}</strong></p>
            </div>
          </div>
        </div>
      </div>
    </div>

    <h5>Memory Tray Information</h5>

    <!-- Card -->
  <!-- <div class="d-flex justify-content-evenly"> -->
    <div class="align-items-center">
      <div class="row">
        <div class="row justify-content-start">
        {% for card in cam_card %}
          <div class="col-sm-3 mb-4">
            <div class="card shadow-sm">
              <div class="card-header bg-main text-light">
                <h5 class="card-title text-center">{{card.name}}</h5>
              </div>
              <div class="card-body">
                <p class="card-text"><strong>Capacity:</strong>
                  {% for latest_gallery in latest_galleries %}
                    {% if latest_gallery.name.id == card.name.id %}
                      {{latest_gallery.quantity}}                          
                    {% endif %}
                  {% endfor %}
                </p>
                <p class="card-text"><strong>Time Last Detected:</strong>
                  {% for latest_gallery in latest_galleries %}
                    {% if latest_gallery.name.id == card.name.id %}
                      {{latest_gallery.timestamp}}
                    {% endif %}
                  {% endfor %}
                </p>
                <div class="text-center">
                  <a href="{% url 'memory_tray_detector:open-cam' camera_id=card.name.id%}" class="btn btn-primary">Open Ip Camera</a>
                </div>
              </div>
            </div>
          </div>
        {% endfor %}
      </div>
      </div>
    </div> 
  <!-- </div> -->
    <!-- Akhir Card -->

  </div>
{% endblock content %}
  
    