mywebsite/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
from person_detector import views as viewsPersonDetector

from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.login_page, name='login'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('', views.index, name='landing-page'),
    path('person-detector/', include('person_detector.urls')),
    path('memory-tray-detector/', include('memory_tray_detector.urls')),
    path('trash-can-detector/', include('trash_can_detector.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

trash_can_detector/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name = 'trash_can_detector'
urlpatterns = [
    path('', views.home, name='home'),
    path('open-cam/<int:camera_id>/', views.open_cam, name='open-cam'),
    # path('open-cam-local/<int:camera_id>/', views.open_cam_local, name='open-cam-local'),
    path('camera/', views.camera, name='camera'),
    path('camera/add', views.add_camera, name='add-camera'),
    path('camera/delete/<int:delete_id>', views.delete, name='delete-camera'),
    path('camera/delete-checkbox/', views.camera_delete_checkbox, name='delete-camera-checkbox'),
    path('camera/delete-all/', views.camera_delete_all, name='delete-camera-all'),
    path('camera/delete/', views.camera_delete_checkbox, name='delete-camera-checkbox'),
    path('camera/update/<int:update_id>', views.update, name='update-camera'),
    path('gallery/', views.gallery, name='gallery'),
    path('gallery/delete/<int:delete_id>', views.delete_gallery, name='delete-gallery'),
    path('gallery/delete-checkbox/', views.gallery_delete_checkbox, name='delete-gallery-checkbox'),
    path('gallery/delete-all/', views.gallery_delete_all, name='delete-gallery-all'),
    
]

trash_can_detector/models.py
from django.db import models
from django.db.models.signals import post_save, pre_delete
from django.dispatch import receiver

# Model untuk Camera
class Camera(models.Model):
    name = models.CharField(max_length=20)
    description = models.CharField(max_length=50, null = True)
    ip_camera = models.CharField(max_length=100, null=True)
    date_created = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name
    
class ListCamera(models.Model):
    name = models.ForeignKey(Camera, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to='trash_can_detector', null=True)

    def __str__(self):
        return self.name
    
# Ketika suatu instance Camera ditambahkan oleh user maka satu CamCard akan dibuat secara otomatis
@receiver(post_save, sender=Camera)
def create_camcard(sender, instance, created, **kwargs):
    if created:
        CamCard.objects.create(name=instance)

# Models untuk Card yang digunakan untuk menampung informasi dari object yang dipotret yang ditampilkan di page Home
class CamCard(models.Model):
    name = models.ForeignKey(Camera, on_delete=models.CASCADE)

    def __str__(self):
        return self.name.name
    
# Models untuk Gallery 
class Gallery(models.Model):
    name = models.ForeignKey(Camera, on_delete=models.CASCADE)
    picture = models.ImageField(upload_to='trash_can_detector', null=True)
    capacity = models.CharField(max_length=10,null=True)
    timestamp = models.DateTimeField()
    detected_day = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name.name
    
    def delete(self, *args, **kwargs):
        self.picture.delete()
        super().delete(*args, **kwargs)  

    class Meta:
         get_latest_by = 'id'



# Ketika instance Camera dihapus, picture pada class Gallery juga akan dihapus
@receiver(pre_delete, sender=Camera)
def delete_picture(sender, instance, **kwargs):    
    # Menghapus gambar pada class Gallery yang menggunakan Camera sebagai foreign key
    for gallery in Gallery.objects.filter(name=instance):
        gallery.delete()

trash_can_detector/forms.py
from django import forms
from .models import Camera, ListCamera

# Form untuk user menambahkan Camera
class AddCameraForm(forms.ModelForm):
    class Meta:
        model = Camera
        fields = [
            'name',
            'description',
            'ip_camera'
        ]

        widgets = {
            'name': forms.TextInput(
                attrs= {
                    'class': 'form-control',
                    'placeholder': 'This field can not be modified'
                }
            ),
            'description': forms.TextInput(
                attrs= {
                    'class': 'form-control',
                    'placeholder': 'Fill the description'
                }
            ),
            'ip_camera': forms.TextInput(
                attrs= {
                    'class': 'form-control',
                    'placeholder': 'If no ip camera, fill with \'-\', \'None\', or \'none\''
                }
            )
        }

class ListCameraForm(forms.Form):
    name = forms.ModelChoiceField(queryset=Camera.objects.all(), label='Select Trash-Can',widget=forms.Select(attrs={'class': 'form-select'}))
    picture = forms.ImageField(label="Image", widget=forms.FileInput(attrs={'class': 'form-control'}))
    class Meta:
        model = ListCamera
        fields = [
            'name',
            'picture'
        ]

trash_can_detector/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from .models import Camera, CamCard, Gallery
from .forms import AddCameraForm, ListCameraForm
from .filters import CameraFilter, GalleryFilter
from .ml_models.camera import open_camera
from django.conf import settings
from datetime import datetime
from django.utils import timezone
from .ml_models.camera import send_message_to_mqtt
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from tensorflow.keras.models import load_model
from tensorflow.keras.utils import load_img, img_to_array
import numpy as np
from django.db.models import Max

import os


# Count status trash-can
def loadModel(path_model):
    return load_model(path_model)

def prediksi(model, tes_path):
    img = load_img(tes_path, target_size=(150, 150))
    x = img_to_array(img)
    x /= 255
    x = np.expand_dims(x, axis=0)
    images = np.vstack([x])
    predict = model.predict(images)
    if predict[0][0] >= 0.5:
        return 1
    return 0

# path_model = os.path.join(settings.BASE_DIR, 'trash_can_detector', 'ml_models', 'new_model.h5')
# model = loadModel(path_model)

# Page Home
@login_required(login_url='login')
def home(request):
    # Mengakses semua instance CamCard
    cam_card = CamCard.objects.all()

    # Membuat instance form
    forms = ListCameraForm(request.POST or None, request.FILES)

    if request.method == 'POST':
        if forms.is_valid():
            # Mendapatkan data dari form yang valid
            name = forms.cleaned_data.get('name')
            picture = request.FILES['picture']
            current_time = timezone.now()
            # Menyimpan file gambar ke sistem file
            # picture_path = os.path.join(settings.MEDIA_ROOT, picture.name)
            # Menyimpan file gambar ke Cloud Storage
            picture_path = settings.GS_BUCKET_NAME
            with open(picture_path, 'wb') as f:
                for chunk in picture.chunks():
                    f.write(chunk)

            # Menghitung prediksi dengan menggunakan model
            path_model = os.path.join(settings.BASE_DIR, 'trash_can_detector', 'ml_models', 'newest_model.h5')
            model = load_model(path_model)
            result = prediksi(model, picture_path)

            # Menghapus file gambar setelah selesai digunakan
            os.remove(picture_path)

            # result = ''
            if result == 0:
                capacity = 'Not Full'
            else:
                capacity = 'Full'

            # Menyimpan data ke dalam model Gallery
            save_to_gallery = Gallery.objects.create(
                name=name,
                picture=picture,
                capacity=capacity,
                timestamp=current_time
            )
            save_to_gallery.save()

            # Mengirim pesan ke MQTT
            formatted_time = current_time.strftime('%d%m%Y')
            message = {
                'name': str(name),
                'capacity': str(result),
                'timestamp': formatted_time
            }
            send_message_to_mqtt(message)

            # Menambahkan pesan sukses ke dalam messages Django
            pesan = f'Success upload image for {name}'
            messages.success(request, pesan)

    # Menghitung jumlah total cam_card
    total_trash_can = len(cam_card)

        
    latest_galleries = Gallery.objects.all().order_by('name', '-timestamp')
    latest_gallery_dict = {}

    for gallery in latest_galleries:
        if gallery.name_id not in latest_gallery_dict:
            latest_gallery_dict[gallery.name_id] = gallery

    latest_galleries = list(latest_gallery_dict.values())



    # Konteks untuk template
    context = {
        'title': 'Trash Can Detector | Home',
        'cam_card': cam_card,
        'forms': forms,
        'total_trash_can': total_trash_can,
        'latest_galleries': latest_galleries
    }
    return render(request, 'trash_can_detector/home.html', context)


# page camera
@login_required(login_url='login')
def camera(request):
    # Mengakses instance Camera
    camera = Camera.objects.all()

    # Mengimplementasikan filters untuk list camera
    myFilters = CameraFilter(request.GET, queryset=camera)
    camera = myFilters.qs

    # Menghitung jumlah total camera
    total_cam = len(camera)

    # Konteks untuk template
    context = {
        'title': 'Trash Can Detector : Camera',
        'camera': camera,
        'total_cam': total_cam,
        'myFilters': myFilters
    }
    return render(request, 'trash_can_detector/camera.html', context)

camera_open = False
@login_required(login_url='login')
def open_cam(request, camera_id):
    global camera_open

    if request.method == 'GET':

        if not camera_open:
            try:
                camera_open = True
                open_camera(camera_id)

                camera_open = False
            except Exception as e:
                # Tangkap kesalahan dan kirim pesan error ke pengguna
                camera_open = False
                error_message = f"Kamera tidak dapat terbuka. Kesalahan: {str(e)}"
                messages.error(request, error_message)
        else:
            messages.error(request, 'Camera is currently open')

    return redirect('trash_can_detector:home')


# Menambahkan instance Camera
@login_required(login_url='login')
def add_camera(request):
    # Mengakses semua instance Camera
    camera = Camera.objects.all()

    # Membuat instance form untuk menambahkan kamera
    add_form = AddCameraForm(request.POST or None)

    if request.method == 'POST':
        if add_form.is_valid():
            # Mendapatkan data dari form yang valid
            name = add_form.cleaned_data['name']
            ip_camera = add_form.cleaned_data['ip_camera']

            # Validasi agar name dan ip camera yang diinput tidak sama dengan yang sudah ada
            if Camera.objects.filter(name=name).exists():
                messages.error(request, 'Nama sudah ada di database.')
                return redirect('trash_can_detector:camera')
            elif Camera.objects.filter(ip_camera=ip_camera).exists() and ip_camera != 'None' and ip_camera != 'none' and ip_camera != '-':
                messages.error(request, 'Alamat IP Camera sudah ada di database.')
                return redirect('trash_can_detector:camera')

            # Menyimpan data ke dalam model Camera
            add_form.save()

            # Menambahkan pesan sukses ke dalam messages Django
            messages.success(request, 'Added Camera Success')
            return redirect('trash_can_detector:camera')

    # Konteks untuk template
    context = {
        'title': 'Add Camera',
        'action': 'Add',
        'add_form': add_form,
        'camera': camera
    }
    return render(request, 'trash_can_detector/add_camera.html', context)


# Menghapus instance Camera
@login_required(login_url='login')
def delete(request, delete_id):
    # Mengakses objek Camera berdasarkan ID yang ingin dihapus
    cam_object = Camera.objects.get(id=delete_id)
    
    # Menghapus objek Camera dari database
    cam_object.delete()

    # Menambahkan pesan sukses ke dalam messages Django
    messages.success(request, 'Camera berhasil dihapus')

    return redirect('trash_can_detector:camera')


# Untuk menghapus photo di Gallery
@login_required(login_url='login')
def delete_gallery(request, delete_id):
    # Mengakses objek Gallery berdasarkan ID yang ingin dihapus
    gal_object = Gallery.objects.get(id=delete_id)
    
    # Menghapus objek Gallery dari database
    gal_object.delete()

    # Menambahkan pesan sukses ke dalam messages Django
    messages.success(request, 'Deleted Success')

    return redirect('trash_can_detector:gallery')


# Update instance Camera
@login_required(login_url='login')
def update(request, update_id):
    # Mengakses semua instance Camera
    camera = Camera.objects.all()

    # Mengakses objek Camera yang ingin diupdate
    cam_update = Camera.objects.get(id=update_id)

    if request.method == 'POST':
        # Membuat instance form untuk mengupdate kamera
        form_cam_update = AddCameraForm(request.POST or None, instance=cam_update)

        # Mengatur field 'name' menjadi disabled agar tidak dapat diupdate oleh user
        form_cam_update.fields['name'].disabled = True

        if form_cam_update.is_valid():
            # Memeriksa apakah ada perubahan pada field 'ip_camera'
            if 'ip_camera' in form_cam_update.changed_data:
                # Jika ada perubahan pada field 'ip_camera'
                ip_camera = form_cam_update.cleaned_data['ip_camera']
                if Camera.objects.filter(ip_camera=ip_camera).exists() and ip_camera != 'None' and ip_camera != 'none' and ip_camera != '-':
                    messages.error(request, 'Alamat IP Camera sudah ada di database.')
                    return redirect('trash_can_detector:camera')

            # Menyimpan perubahan pada objek Camera
            form_cam_update.save()

            # Menambahkan pesan sukses ke dalam messages Django
            messages.success(request, 'Updated Succes')
            return redirect('trash_can_detector:camera')
    else:
        # Membuat instance form dengan objek Camera yang ingin diupdate
        form_cam_update = AddCameraForm(instance=cam_update)

        # Mengatur field 'name' menjadi disabled agar tidak dapat diupdate oleh user
        form_cam_update.fields['name'].disabled = True

    # Konteks untuk template
    context = {
        'title': 'Update Camera',
        'action': 'Update',
        'add_form': form_cam_update,
        'camera': camera
    }

    return render(request, 'trash_can_detector/add_camera.html', context)


# Page Gallery
@login_required(login_url='login')
def gallery(request):
    # Mengakses semua instance dalam Gallery dan diurutkan dari yang paling baru
    gall = Gallery.objects.all().order_by('-id')

trash_can_detector/templates/trash_can_detector/add_camera.html
{% extends 'trash_can_detector/camera.html' %}

{% block add_camera %}
    
    <div class="container shadow rounded mt-3">
        <h5>{{title}}</h5>
        <form method="POST" enctype="multipart/form-data" class="col">
            {% csrf_token %}
                
            {% for form in add_form %}
                <div class="col-auto">
                    {{form.label}}
                </div>                        
                        
                <div class="col-auto">
                    {{form}}
                </div>
            {% endfor %}

            <button type="submit" class="btn btn-success my-4">Submit</button>
            <a href="{% url 'trash_can_detector:camera' %}" class="btn btn-danger">Back</a>

        </form>
    </div> 

{% endblock add_camera %}
    

trash_can_detector/templates/trash_can_detector/camera.html
{% extends 'base.html' %}


{% block title %}
    {{title}}
{% endblock title %}
    
{% block list %}
  <li class="nav-item ps-4">
    <a class="nav-link" href="{% url 'trash_can_detector:home' %}">Home</a>
  </li>
  <li class="nav-item ps-4">
    <a class="nav-link active" aria-current="page" href="{% url 'trash_can_detector:camera' %}">Camera</a>
  </li>
  <li class="nav-item ps-4">
    <a class="nav-link" href="{% url 'trash_can_detector:gallery' %}">Gallery</a>
  </li>
  <li class="nav-item ps-4">
    <a class="nav-link" href="" data-bs-toggle="modal" data-bs-target="#logout-user">Logout</a>
  </li>    
{% endblock list %}


{% block content %}
  
  {% block add_camera %}
    
  {% endblock add_camera %}
    
  <div class="container mt-3" style="font-family: 'Poppins', sans-serif; font-weight: 400;">

    <!-- modal untuk logout -->
    <div class="modal fade" id="logout-user" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header bg-main text-light">
            <h1 class="modal-title fs-5" id="exampleModalLabel">LOGOUT</h1>
            <button type="button" class="btn-close bg-light" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <div class="modal-body">
            Are you sure to <strong>Logut</strong>?
          </div>
          <div class="modal-footer">
            <a href="{% url 'logout' %}" class="btn btn-danger">Logout</a>
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
          </div>
        </div>
      </div>
    </div>

    <!-- Title -->
    <div class="d-flex justify-content-between">
      <h5>Trash Can Detector | Home </h5>
      <h5>Active | {{user.first_name}}</h5>
    </div>
    <!-- Button Add Camera -->
    <a href="{% url 'trash_can_detector:add-camera' %}" class="btn btn-primary my-1">Add Camera</a>
    <!-- messages -->
    <div>
      {% if messages %}
        {% for msg in messages %}
            <div class="alert {% if msg.tags == 'success' %}alert-success{% elif msg.tags == 'error' %}alert-danger{% endif %} alert-dismissible fade show d-sm-inline-flex" role="alert">
                {{ msg }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endfor %}
      {% endif %}
    </div>

     <!-- Filter -->
     <div class="row mt-2 mb-2">
      <div class="col">
        <div class="card card-body">
          <div class="d-flex justify-content-between">
            <div>
              <form method="GET" class="row g-2 align-items-center">
                <div class="col-auto align-middle">
                  {{myFilters.form.name.label}}
                </div>
                <div class="col-auto">
                  {{myFilters.form.name}}
                </div>                    
                <div class="col-auto">
                  <button type="submit" class="btn btn-primary">Search</button>
                </div>
                <div class="col-auto">
                  <a href="{% url 'trash_can_detector:camera' %}" class="btn btn-danger">Back to See All</a>
                </div>
              </form>
            </div>
            <div>
              <p>Current Data : <strong>{{total_cam}}</strong></p>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Akhir -->
    
     <!-- Tabel -->
     <div class="scroll">
      <form action="{% url 'trash_can_detector:delete-camera-checkbox' %}" method="post">
        {% csrf_token %}
        <table class="table table-striped table-hover table-bordered rounded rounded-lg">
          <thead>
            <tr>
              <th scope="col" class="text-center align-middle">No.</th>
              <th scope="col" class="text-center align-middle">Name</th>
              <th scope="col" class="text-center align-middle">Description</th>
              <th scope="col" class="text-center align-middle">IP Camera</th>
              <th scope="col" class="text-center align-middle">Date Created</th>
              <th scope="col" class="text-center align-middle">
                Delete
                    <div class="btn-group">
                      <button type="button" class="btn btn-sm bg-main text-light dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false"></button>
                      <ul class="dropdown-menu">
                        <li><button type="button" class="dropdown-item" data-bs-toggle="modal" data-bs-target="#delete-all-data">Delete All</button></li>
                      </ul>
              </th>
              <!-- Modal Delete All-->
              <div class="modal fade" id="delete-all-data" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                  <div class="modal-content">
                    <div class="modal-header bg-main text-light">
                      <h1 class="modal-title fs-5" id="exampleModalLabel">DELETE</h1>
                      <button type="button" class="btn-close bg-light" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      Are you sure to delete <strong>All Data</strong>?. This action will delete all information and photo in gallery
                    </div>
                    <div class="modal-footer">
                      <a href="{% url 'trash_can_detector:delete-camera-all' %}" class="btn btn-danger">Delete</a>
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    </div>
                  </div>
                </div>
              </div>
              <!-- Akhir modal -->
              <th scope="col" class="text-center align-middle">Update</th>
              <th scope="col" class="text-center align-middle">
                <button type="button" class="btn btn-sm btn-danger" data-bs-toggle="modal" data-bs-target="#delete-selected">Delete</button>
              </th>
              <!-- Modal Delete Selected-->
              <div class="modal fade" id="delete-selected" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog modal-dialog-centered">
                  <div class="modal-content">
                    <div class="modal-header bg-main text-light">
                      <h1 class="modal-title fs-5" id="exampleModalLabel">DELETE</h1>
                      <button type="button" class="btn-close bg-light" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body">
                      Are you sure to delete the data of <strong>Selected Data</strong>?. This action will delete all of part the <strong>Selected</strong>, include all information and photo in gallery
                    </div>
                    <div class="modal-footer">
                      <button type="submit" class="btn btn-danger">Delete</button>
                      <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                    </div>
                  </div>
                </div>
              </div>
              <!-- Akhir modal -->
            </tr>
          </thead>
          <tbody>
            {% for data in camera %}
              <tr>
                <td scope="row" class="text-center align-middle">{{forloop.counter}}</td>
                <td class="text-center align-middle">{{data.name}}</td>
                <td class="text-center align-middle">{{data.description}}</td>
                <td class="text-center align-middle">{{data.ip_camera}}</td>
                <td class="text-center align-middle">{{data.date_created}}</td>
                <td class="text-center align-middle">
                  <button type="button" class="btn btn-sm btn-danger" data-bs-toggle="modal" data-bs-target="#delete-{{data.id}}">
                    Delete
                  </button>
                </td>
                <!-- Modal -->
                <div class="modal fade" id="delete-{{data.id}}" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
                  <div class="modal-dialog modal-dialog-centered">
                    <div class="modal-content">
                      <div class="modal-header bg-main text-light">
                        <h1 class="modal-title fs-5" id="exampleModalLabel">DELETE</h1>
                        <button type="button" class="btn-close bg-light" data-bs-dismiss="modal" aria-label="Close"></button>
                      </div>
                      <div class="modal-body">
                        Are you sure to delete <strong>"{{data.name}}"</strong> data?
                      </div>
                      <div class="modal-footer">
                        <a href="{% url 'trash_can_detector:delete-camera' data.id %}" class="btn btn-danger">Delete</a>
                        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                      </div>
                    </div>
                  </div>
                </div>
                <td class="text-center align-middle">
                  <a href="{% url 'trash_can_detector:update-camera' data.id %}" class="btn btn-sm btn-warning">Update</a>
                </td>
                <td class="text-center align-middle">
                  <input type="checkbox" class="camera-checkbox" name="camera_ids" value="{{data.id}}">
                </td>
              </tr>
            {% endfor %}             
          </tbody>
        </table>
      </form>
    </div>
    <!-- Akhir Tabel -->
  
  
  
  
  
  </div>

  <script>
    // Mengambil semua elemen checkbox dengan class 'camera-checkbox'
    const checkboxes = document.querySelectorAll('.camera-checkbox');

    // Mendaftarkan event listener untuk setiap checkbox
    checkboxes.forEach(checkbox => {
      // Menambahkan event listener untuk klik pada kotak centang
      checkbox.addEventListener('click', (event) => {
        // Mencegah klik pada kotak centang mempengaruhi perilaku
        event.stopPropagation();
      });

      // Menambahkan event listener untuk klik pada kolom
      checkbox.parentNode.addEventListener('click', (event) => {
        // Toggle status kotak centang saat kolom diklik
        checkbox.checked = !checkbox.checked;
      });
    });
  </script>
{% endblock content %}
  
    

trash_can_detector/templates/trash_can_detector/login.html
{% extends 'base.html' %}


{% block title %}
    {{title}}    
{% endblock title %}

    

{% block content %}
 <div class="container">

 
    <!-- messages -->
 {% if messages %}
 {% for msg in messages %}
     <div class="alert {% if msg.tags == 'success' %}alert-success{% elif msg.tags == 'error' %}alert-danger{% endif %} alert-dismissible fade show d-sm-inline-flex mt-2" role="alert">
         {{ msg }}
         <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
     </div>
 {% endfor %}
{% endif %}


<!-- Login Card -->
    <div class="row d-flex justify-content-center mt-5">
        <div class="col-md-4">
            <div class="card shadow">
                <div class="card-header bg-main text-light align-middle">
                    <h6 class="text-center">LOGIN PAGE | TRASH CAN DETECTOR DETECTOR</h6>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
    
                        <div class="col-auto">
                            <label for="username" class="form-label">Username:</label>
                            <input type="text" class="form-control" id="username" name="username">
                          </div>
                          <div class="mb-3">
                            <label for="password" class="form-label">Password</label>
                            <input type="password" class="form-control" id="password" name="password">
                          </div>
    
                          <button type="submit" class="btn btn-primary">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
 </div>    

{% endblock content %}
    

trash_can_detector/templates/trash_can_detector/logout.html
{% extends 'base.html' %}

{% block title %}
    {{title}}
{% endblock title %}
    
{% block list %}
  <li class="nav-item ps-4">
    <a class="nav-link" href="{% url 'trash_can_detector:home' %}">Home</a>
  </li>
  <li class="nav-item ps-4">
    <a class="nav-link" href="{% url 'trash_can_detector:camera' %}">Camera</a>
  </li>
  <li class="nav-item ps-4">
    <a class="nav-link" href="{% url 'trash_can_detector:gallery' %}">Gallery</a>
  </li>
  <li class="nav-item ps-4">
    <a class="nav-link active" aria-current="page" href="{% url 'trash_can_detector:logout' %}">Log Out</a>
  </li>    
{% endblock list %}

{% block content %}
    <h5>Trash Can Detector | Gallery</h5>
{% endblock content %}
    