memory_tray_detector/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name = 'memory_tray_detector'
urlpatterns = [
    path('', views.home, name='home'),
    path('open-cam/<int:camera_id>/', views.open_cam, name='open-cam'),
    # path('open-cam-local/<int:camera_id>/', views.open_cam_local, name='open-cam-local'),
    path('camera/', views.camera, name='camera'),
    path('camera/add', views.add_camera, name='add-camera'),
    path('camera/delete/<int:delete_id>', views.delete, name='delete-camera'),
    path('camera/delete-checkbox/', views.camera_delete_checkbox, name='delete-camera-checkbox'),
    path('camera/delete-all/', views.camera_delete_all, name='delete-camera-all'),
    path('camera/update/<int:update_id>', views.update, name='update-camera'),
    path('gallery/', views.gallery, name='gallery'),
    path('gallery/delete/<int:delete_id>', views.delete_gallery, name='delete-gallery'),
    path('gallery/delete-checkbox/', views.gallery_delete_checkbox, name='delete-gallery-checkbox'),
    path('gallery/delete-all/', views.gallery_delete_all, name='delete-gallery-all'),    
]

mywebsite/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views
from person_detector import views as viewsPersonDetector

from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth.views import LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', views.login_page, name='login'),
    path('logout/', LogoutView.as_view(next_page='login'), name='logout'),
    path('', views.index, name='landing-page'),
    path('person-detector/', include('person_detector.urls')),
    path('memory-tray-detector/', include('memory_tray_detector.urls')),
    path('trash-can-detector/', include('trash_can_detector.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

person_detector/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name = 'person_detector'
urlpatterns = [
    path('', views.home, name='home'),
    path('database/', views.database, name='database'),
    path('database/add/', views.post_database, name='add-database'),
    # path('database/train/', views.train_data, name='train_data'),
    path('open/', views.cam, name='open_cam'),
    path('database/delete/<int:delete_id>', views.delete, name='delete_data'),
    path('database/delete-checkbox/', views.person_delete_checkbox, name='delete-person-checkbox'),
    path('database/delete-all/', views.person_delete_all, name='delete-person-all'),
    path('database/update/<int:update_id>', views.update, name='update_data'),
    path('database/update-ip-camera/<int:update_id>', views.update_ip_camera, name='update_ip_camera'),
    path('reset-all-detected-face/', views.reset_all, name='reset-all-detected-face'),
    path('export/', views.export_detected_dace, name='export-detected-face'),
    # path('gallery/', views.gallery, name='gallery'),
]

trash_can_detector/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView
from . import views

app_name = 'trash_can_detector'
urlpatterns = [
    path('', views.home, name='home'),
    path('open-cam/<int:camera_id>/', views.open_cam, name='open-cam'),
    # path('open-cam-local/<int:camera_id>/', views.open_cam_local, name='open-cam-local'),
    path('camera/', views.camera, name='camera'),
    path('camera/add', views.add_camera, name='add-camera'),
    path('camera/delete/<int:delete_id>', views.delete, name='delete-camera'),
    path('camera/delete-checkbox/', views.camera_delete_checkbox, name='delete-camera-checkbox'),
    path('camera/delete-all/', views.camera_delete_all, name='delete-camera-all'),
    path('camera/delete/', views.camera_delete_checkbox, name='delete-camera-checkbox'),
    path('camera/update/<int:update_id>', views.update, name='update-camera'),
    path('gallery/', views.gallery, name='gallery'),
    path('gallery/delete/<int:delete_id>', views.delete_gallery, name='delete-gallery'),
    path('gallery/delete-checkbox/', views.gallery_delete_checkbox, name='delete-gallery-checkbox'),
    path('gallery/delete-all/', views.gallery_delete_all, name='delete-gallery-all'),
    
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>        
        {% block title %}
            
        {% endblock title %}
    </title>
    <!-- google font -->
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,400;0,500;0,600;0,700;1,400;1,500;1,600;1,700&display=swap" rel="stylesheet">

    <!-- bootstrap CSS-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <style>
      .scroll {
        height: 600px;
        overflow-y: scroll;
        overflow-x: scroll;
      }

      table thead {
        position: sticky;
        top: 0px;
        /* background-color: #0d6efd; */
        background-color: #0A306A;
        color: white;
      }

      .bg-main {
        background-color: #0A306A;
      }

      .bg-true {
        background-color: #1E90FF;
      }

      .bg-false {
        background-color: #E74646;
      }
    </style>

    
    {% block style %}
      
    {% endblock style %}
      

    <!-- bahan untuk membuka calender -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">
    <script src="https://cdn.jsdelivr.net/npm/flatpickr"></script>

    <!-- Icon -->
    <link rel="shortcut icon" href="{% static 'images/main/wowrack.png' %}">
</head>
<body>
    <nav class="navbar navbar-expand-lg bg-main navbar-dark shadow-sm" style="font-family: 'Poppins', sans-serif; font-weight: 500;">
        <div class="container">
          <a class="navbar-brand" href="{% url 'landing-page' %}">Wowrack Indonesia</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
              
              {% block list %}
                
              {% endblock list %}
                
            </ul>
          </div>
        </div>
      </nav>

    {% block content %}
        
    {% endblock content %}
        

    <!-- Bootsrtap js -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.min.js" integrity="sha384-cuYeSxntonz0PPNlHhBs68uyIAVpIIOZZ5JqeqvYYIcEL727kskC66kF92t6Xl2V" crossorigin="anonymous"></script>
    <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script> -->
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    {{title}}
{% endblock title %}


{% block list %}
  <li class="nav-item ps-4">
    <a class="nav-link" href="{% url 'person_detector:home' %}">Person Detector</a>
  </li>
  <li class="nav-item ps-4">
    <a class="nav-link" href="{% url 'memory_tray_detector:home' %}">Memory Tray Detector</a>
  </li>
  <li class="nav-item ps-4">
    <a class="nav-link" href="{% url 'trash_can_detector:home' %}">Trash Can Detector</a>
  </li>    
  <li class="nav-item ps-4">
    <a class="nav-link" href="" data-bs-toggle="modal" data-bs-target="#logout">Logout</a>
  </li>
{% endblock list %}


{% block style %}
    <style>
    body {
        background-color: #0A306A;
    }
    </style>
{% endblock style %}
    


{% block content %}
    <div class="container mt-3" style="font-family: 'Poppins', sans-serif; font-weight: 400;">
    
        <!-- modal untuk logout -->
        <div class="modal fade" id="logout" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header bg-main text-light">
                <h1 class="modal-title fs-5" id="exampleModalLabel">LOGOUT</h1>
                <button type="button" class="btn-close bg-light" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                Are you sure to <strong>Logout</strong>?
                </div>
                <div class="modal-footer">
                <a href="{% url 'logout' %}" class="btn btn-danger">Logout</a>
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cancel</button>
                </div>
            </div>
            </div>
        </div>

        <h1 class="text-center text-light mt-5">Person and Object Detectors</h1>

        <!-- Jumbotron -->
        <section class="jumbotron text-center " id="jumbotron">
            <img src="{% static 'images/main/jumbotron.png' %}" alt="" width="450" class="jumbotron-img">
            <h1 class="text-light mt-4">Welcome, <strong>{{user.first_name}}</strong>!</h1>
        </section>
        <!-- Akhir Jumbotron -->
    
    
    </div>
{% endblock content %}
    
    
    

templates/login.html
{% extends 'base.html' %}


{% block title %}
    {{title}}    
{% endblock title %}

{% block style %}
    <style>
    body {
        background-color: #0A306A;
    }
    </style>
{% endblock style %}
    

{% block content %}
 <div class="container">

 
 
<br><br><br><br>

<!-- Login Card -->
    <div class="row justify-content-center align-items-center mt-5">
        <div class="col-md-4">
            <div class="card shadow">
                <div class="card-header bg-main text-light align-middle">
                    <h6 class="text-center">LOGIN PAGE</h6>
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                           <!-- messages -->
                            {% if messages %}
                            {% for msg in messages %}
                                <div class="alert {% if msg.tags == 'success' %}alert-success{% elif msg.tags == 'error' %}alert-info{% endif %} alert-dismissible fade show d-sm-inline-flex mt-2" role="alert">
                                    {{ msg }}
                                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                                </div>
                            {% endfor %}
                            {% endif %}

                         <div class="col-auto mb-2">
                            <label for="username" class="form-label">Username:</label>
                            <input type="text" class="form-control" id="username" name="username">
                          </div>
                          <div class="col-auto mb-3">
                            <label for="password" class="form-label">Password:</label>
                            <input type="password" class="form-control" id="password" name="password"> 
                          </div>
    
                          <button type="submit" class="btn" style="background-color: #0A306A; color: white;">Login</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
 </div>    

{% endblock content %}
    